# Generated by Django 4.2.7 on 2024-11-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_library', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
