# Generated by Django 4.2.7 on 2024-11-25 14:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_library', '0004_recipe_prep_time_recipe_serves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dietary_choices',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Vegetarian'), (2, 'Vegan'), (3, 'Gluten Free'), (4, 'Lactose Free'), (5, 'Nut free')], max_length=9),
        ),
    ]
