# Generated by Django 4.2.7 on 2024-11-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_library', '0005_alter_recipe_dietary_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Under review'), (1, 'Published')], default=0),
        ),
    ]
