# Generated by Django 4.2.7 on 2024-12-04 09:50

import cloudinary.models
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_library', '0007_alter_recipe_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dietary_choices',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Vegetarian'), (2, 'Vegan'), (3, 'Gluten Free'), (4, 'Lactose Free'), (5, 'Nut free')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
