# Generated by Django 4.2.7 on 2024-12-04 10:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_library', '0008_alter_recipe_dietary_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dietary_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Vegetarian'), (2, 'Vegan'), (3, 'Gluten Free'), (4, 'Lactose Free'), (5, 'Nut free')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(),
        ),
    ]
